FROM docker:dind

COPY ./authz.rego /etc/docker/policies/authz.rego
COPY ./daemon.json /etc/docker/daemon.json_plugin
COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
